# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: post.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\npost.proto\x1a\x1bgoogle/protobuf/empty.proto\"3\n\x14GeneratePostsRequest\x12\x0b\n\x03uid\x18\x01 \x01(\t\x12\x0e\n\x06prompt\x18\x02 \x01(\t\"\x19\n\x04Post\x12\x11\n\tphoto_src\x18\x01 \x01(\t\"b\n\x14GeneratePostResponse\x12\x15\n\x04post\x18\x01 \x01(\x0b\x32\x05.PostH\x00\x12\'\n\x05\x65mpty\x18\x02 \x01(\x0b\x32\x16.google.protobuf.EmptyH\x00\x42\n\n\x08response2P\n\x0bPostService\x12\x41\n\rGeneratePosts\x12\x15.GeneratePostsRequest\x1a\x15.GeneratePostResponse\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'post_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_GENERATEPOSTSREQUEST']._serialized_start=43
  _globals['_GENERATEPOSTSREQUEST']._serialized_end=94
  _globals['_POST']._serialized_start=96
  _globals['_POST']._serialized_end=121
  _globals['_GENERATEPOSTRESPONSE']._serialized_start=123
  _globals['_GENERATEPOSTRESPONSE']._serialized_end=221
  _globals['_POSTSERVICE']._serialized_start=223
  _globals['_POSTSERVICE']._serialized_end=303
# @@protoc_insertion_point(module_scope)
